kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: zero-dev-admin-access
  namespace: zero-dev
subjects:
- kind: ServiceAccount
  name: zero-dev-service-account
#  apiGroup: rbac.authorization.k8s.io
  namespace: zero-dev
roleRef:
  kind: Role 
  name: admin-role
  apiGroup: rbac.authorization.k8s.io
