kind: ConfigMap
apiVersion: v1
metadata:
  name: zero-nginx-configuration
  namespace: zero-nginx
  labels:
    app: zeor-nginx
    resource: nginx-configuration
    type: configmap

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: zero-nginx-tcp
  namespace: zero-nginx
  labels:
    app: zeor-nginx
    resource: nginx-tcp
    type: configmap

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: zero-nginx-upd
  namespace: zero-nginx
  labels:
    app: zeor-nginx
    resource: nginx-udp
    type: configmap
