apiVersion: v1
kind: ServiceAccount
metadata:
  name: zero-nginx-serviceaccount
  namespace: zero-nginx
  labels:
    app: zero-nginx
    resource: serviceaccount
    type: serviceaccount

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: zero-nginx-clusterrole
  labels:
    app: zero-nginx
    resource: clusterrole
    type: clusterrole
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - endpoints
      - nodes
      - pods
      - secrets
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "extensions"
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - "extensions"
    resources:
      - ingresses/status
    verbs:
      - update

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: zero-nginx-role
  namespace: zero-nginx
  labels:
    app: zero-nginx
    resource: role
    type: role
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - pods
      - secrets
      - namespaces
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      # Defaults to "<election-id>-<ingress-class>"
      # Here: "<ingress-controller-leader>-<nginx>"
      # This has to be adapted if you change either parameter
      # when launching the nginx-ingress-controller.
      - "ingress-controller-leader-nginx"
    verbs:
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - get

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: zero-nginx-rolebinding
  namespace: zero-nginx
  labels:
    app: zero-nginx
    resource: rolebinding
    type: rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: zero-nginx-role
subjects:
  - kind: ServiceAccount
    name: zero-nginx-serviceaccount
    namespace: zero-nginx

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: zero-nginx-clusterrolebinding
  labels:
    app: zero-nginx
    resource: clusterrolebinding
    type: clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: zero-nginx-clusterrole
subjects:
  - kind: ServiceAccount
    name: zero-nginx-serviceaccount
    namespace: zero-nginx
